import { ROLE_PRESETS } from './roles/index.js';
import type { PersonalityPreset } from './schemas.js';
import type { ToolCapability } from '@ujima/shared';
export const DEFAULT_TOOL_CATALOG: Record<string, ToolCapability> = {
  view: {
    id: 'view',
    name: 'View',
    description:
      'Read a workspace file in a numbered window. Accepts file_path plus lines ("1-100", "120-", "42"), or offset+limit. Default reads only the first 200 lines — use lines or limit to widen, and prefer the smallest window that answers your question. Reading the same file twice in one run replays it on every step, so re-target instead of re-reading.',
    actions: ['read'],
    pathScopes: ['.'],
    requiresApproval: false,
  },
  write: {
    id: 'write',
    name: 'Write',
    description: 'Create or overwrite one workspace file with full content. Use for new files or large rewrites. Accepts file_path and content. For surgical edits use edit or multiedit.',
    actions: ['write'],
    pathScopes: ['.'],
    requiresApproval: true,
  },
  edit: {
    id: 'edit',
    name: 'Edit',
    description: 'Edit one file by exact find-and-replace. Accepts file_path, old_string, new_string, and replace_all. Prefer this over shell for small file changes.',
    actions: ['write'],
    pathScopes: ['.'],
    requiresApproval: true,
  },
  multiedit: {
    id: 'multiedit',
    name: 'Multi Edit',
    description: 'Apply multiple exact find-and-replace edits to one file in order. Accepts file_path and edits with old_string/new_string. Prefer this over shell for multiple changes in one file.',
    actions: ['write'],
    pathScopes: ['.'],
    requiresApproval: true,
  },
  ls: {
    id: 'ls',
    name: 'List',
    description: 'List workspace files and folders from a path.',
    actions: ['read'],
    pathScopes: ['.'],
    requiresApproval: false,
  },
  glob: {
    id: 'glob',
    name: 'Glob',
    description: 'Find workspace files matching a glob pattern.',
    actions: ['read'],
    pathScopes: ['.'],
    requiresApproval: false,
  },
  grep: {
    id: 'grep',
    name: 'Grep',
    description: 'Search visible workspace files for matching lines, then use view for a focused window around the hit.',
    actions: ['read'],
    pathScopes: ['.'],
    requiresApproval: false,
  },
  fetch: {
    id: 'fetch',
    name: 'Fetch',
    description: 'Fetch a URL and return its response body.',
    actions: ['read'],
    pathScopes: [],
    requiresApproval: false,
  },
  download: {
    id: 'download',
    name: 'Download',
    description: 'Download a URL into a workspace file.',
    actions: ['write'],
    pathScopes: ['.'],
    requiresApproval: true,
  },
  job_output: {
    id: 'job_output',
    name: 'Job Output',
    description: 'Read buffered output for a background shell job.',
    actions: ['read'],
    pathScopes: [],
    requiresApproval: false,
  },
  job_kill: {
    id: 'job_kill',
    name: 'Job Kill',
    description: 'Stop a background shell job.',
    actions: ['execute'],
    pathScopes: [],
    requiresApproval: true,
  },
  shell: {
    id: 'shell',
    name: 'Shell',
    description: 'Run local commands inside the organization workspace for builds, tests, git, and real CLI work. Do not create or edit files with shell redirection, heredocs, sed/perl/python scripts, or tee; use write, edit, or multiedit.',
    actions: ['execute'],
    pathScopes: ['.'],
    requiresApproval: true,
  },
  web_search: {
    id: 'web_search',
    name: 'Web Search',
    description: 'Search the web for live results using a provider-backed search path with DuckDuckGo fallback.',
    actions: ['read'],
    pathScopes: [],
    requiresApproval: false,
  },
  message: {
    id: 'message',
    name: 'Message',
    description: 'Send messages to channels, threads, and direct message recipients. Use ignore on DMs only for a private note, not for skipping a real reply.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  schedule: {
    id: 'schedule',
    name: 'Schedule',
    description: 'Create, list, or cancel recurring schedules for an organization.',
    actions: ['read', 'execute'],
    pathScopes: [],
    requiresApproval: false,
  },
  'channel.post': {
    id: 'channel.post',
    name: 'Channel Post',
    description: 'Post a new message to a channel. Use channel.reply for replies in an existing thread. Write @mentions with display names, not raw ids.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  'channel.reply': {
    id: 'channel.reply',
    name: 'Channel Reply',
    description: 'Reply to a message inside its existing thread.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  'channel.dm': {
    id: 'channel.dm',
    name: 'Channel DM',
    description: 'Send a direct message, lazily creating the DM channel when needed. Use ignore for a private DM that skips wake fanout, not for deciding whether to reply.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  'channel.list': {
    id: 'channel.list',
    name: 'Channel List',
    description: 'List visible channels in the organization.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  'channel.read': {
    id: 'channel.read',
    name: 'Channel Read',
    description: 'Read recent or searched messages from a channel.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  'channel.recall': {
    id: 'channel.recall',
    name: 'Channel Recall',
    description: 'Recall prior channel context and artifacts across conversations.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  'goal.start': {
    id: 'goal.start',
    name: 'Goal Start',
    description: 'Open the channel goal board with a plan and a task list. Use ONLY for kicking off a fresh project; once the goal exists, evolve it via goal_task_update (do not call goal_start twice for the same plan).',
    actions: ['create'],
    pathScopes: [],
    requiresApproval: false,
  },
  'goal.task.update': {
    id: 'goal.task.update',
    name: 'Goal Task Update',
    description: 'THE task tracking system for this org. Update a task by its task_id: change status (pending/in_progress/completed/blocked/failed/cancelled), record a handover_summary, or — supervisors only — edit title, description, or assignee_id. Always call this when anyone asks to update task status or move a card on the board.',
    actions: ['update'],
    pathScopes: [],
    requiresApproval: false,
  },
  'goal.channel.view': {
    id: 'goal.channel.view',
    name: 'Goal Channel View',
    description: 'Read the active goal board and tasks for a specific channel, or for the current channel when no id is provided.',
    actions: ['read'],
    pathScopes: [],
    requiresApproval: false,
  },
  'question.ask': {
    id: 'question.ask',
    name: 'Question Ask',
    description: 'Pose a structured multiple-choice question to a human and pause the run until they pick an option.',
    actions: ['create'],
    pathScopes: [],
    requiresApproval: false,
  },
  'memory.write': {
    id: 'memory.write',
    name: 'Memory Write',
    description: 'Save a durable memory fact, decision, action summary, or correction to persist across runs and channels.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  'memory.recall': {
    id: 'memory.recall',
    name: 'Memory Recall',
    description: 'Recall active memories to maintain cross-spirit consistency across DMs and channels.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  'org.members.list': {
    id: 'org.members.list',
    name: 'Organization Members List',
    description: 'List active organization members so staffing decisions can be made from the current roster.',
    actions: ['read'],
    pathScopes: [],
    requiresApproval: false,
  },
  'org.members.add': {
    id: 'org.members.add',
    name: 'Organization Members Add',
    description: 'Add a new agent member to the organization with the supplied role, model, and channel membership.',
    actions: ['write'],
    pathScopes: [],
    requiresApproval: false,
  },
  'org.members.update': {
    id: 'org.members.update',
    name: 'Organization Members Update',
    description: 'Update an existing agent member, including role, channels, provider, model, and instructions.',
    actions: ['write'],
    pathScopes: [],
    requiresApproval: false,
  },
  'org.members.remove': {
    id: 'org.members.remove',
    name: 'Organization Members Remove',
    description: 'Retire an existing agent member from the organization.',
    actions: ['write'],
    pathScopes: [],
    requiresApproval: false,
  },
  'org.organization.get': {
    id: 'org.organization.get',
    name: 'Organization Get',
    description: 'Read current organization settings, members, and visible channels.',
    actions: ['read'],
    pathScopes: [],
    requiresApproval: false,
  },
  'org.organization.update': {
    id: 'org.organization.update',
    name: 'Organization Update',
    description: 'Update top-level organization settings such as workspace name or workspace root.',
    actions: ['write'],
    pathScopes: [],
    requiresApproval: false,
  },
  'org.policies.update': {
    id: 'org.policies.update',
    name: 'Organization Policies Update',
    description: 'Update organization policy settings such as write approval and shell approval mode.',
    actions: ['write'],
    pathScopes: [],
    requiresApproval: false,
  },
  mcp: {
    id: 'mcp',
    name: 'MCP',
    description: 'Call an approved MCP server by mcpServerId and toolName. Pass tool arguments in args.',
    actions: ['mcp'],
    pathScopes: [],
    requiresApproval: true,
  },
};

export const PERSONALITY_PRESETS: Record<string, PersonalityPreset> = {
  direct: {
    name: 'direct',
    title: 'Direct',
    description: 'Brief, decisive, and low on fluff.',
    instructions:
      'Speak plainly and get to the point. Prefer short, actionable responses. Do not over-explain when a clear answer exists.',
  },
  thoughtful: {
    name: 'thoughtful',
    title: 'Thoughtful',
    description: 'Balances action with careful consideration.',
    instructions:
      'Slow down enough to notice tradeoffs and hidden assumptions. When the answer is uncertain, say so and explain the decision path.',
  },
  precise: {
    name: 'precise',
    title: 'Precise',
    description: 'Exact, rigorous, and detail-oriented.',
    instructions:
      'Be exact about names, numbers, paths, and constraints. Avoid vague language. Call out anything that needs verification.',
  },
  warm: {
    name: 'warm',
    title: 'Warm',
    description: 'Collaborative and easy to work with.',
    instructions:
      'Be friendly and encouraging without losing clarity. Help the team move forward with a calm, human tone.',
  },
  skeptical: {
    name: 'skeptical',
    title: 'Skeptical',
    description: 'Questions assumptions and looks for failure modes.',
    instructions:
      'Pressure-test claims, look for edge cases, and challenge unsafe or unproven plans. Prefer proof over optimism.',
  },
  pragmatic: {
    name: 'pragmatic',
    title: 'Pragmatic',
    description: 'Biases toward the simplest working path.',
    instructions:
      'Choose the smallest implementation that solves the problem. Avoid unnecessary abstraction and keep decisions grounded in current constraints.',
  },
};

export { ROLE_PRESETS };
