import { ROLE_PRESETS } from './roles/index.js';
import type { PersonalityPreset } from './schemas.js';
import type { ToolCapability } from '@ujima/shared';
export const DEFAULT_TOOL_CATALOG: Record<string, ToolCapability> = {
  view: {
    id: 'view',
    name: 'View',
    description:
      'Read a workspace file in a numbered window. Accepts file_path plus lines ("1-100", "120-", "42"), or offset+limit. Default reads only the first 200 lines — use lines or limit to widen, and prefer the smallest window that answers your question. Reading the same file twice in one run replays it on every step, so re-target instead of re-reading.',
    actions: ['read'],
    pathScopes: ['.'],
    requiresApproval: false,
  },
  write: {
    id: 'write',
    name: 'Write',
    description: 'Create or overwrite one workspace file with full content. Use for new files or large rewrites. Accepts file_path and content. For surgical edits use edit or multiedit.',
    actions: ['write'],
    pathScopes: ['.'],
    requiresApproval: true,
  },
  edit: {
    id: 'edit',
    name: 'Edit',
    description: 'Edit one file by exact find-and-replace. Accepts file_path, old_string, new_string, and replace_all. Prefer this over shell for small file changes.',
    actions: ['write'],
    pathScopes: ['.'],
    requiresApproval: true,
  },
  multiedit: {
    id: 'multiedit',
    name: 'Multi Edit',
    description: 'Apply multiple exact find-and-replace edits to one file in order. Accepts file_path and edits with old_string/new_string. Prefer this over shell for multiple changes in one file.',
    actions: ['write'],
    pathScopes: ['.'],
    requiresApproval: true,
  },
  ls: {
    id: 'ls',
    name: 'List',
    description: 'List workspace files and folders from a path.',
    actions: ['read'],
    pathScopes: ['.'],
    requiresApproval: false,
  },
  glob: {
    id: 'glob',
    name: 'Glob',
    description: 'Find workspace files matching a glob pattern.',
    actions: ['read'],
    pathScopes: ['.'],
    requiresApproval: false,
  },
  grep: {
    id: 'grep',
    name: 'Grep',
    description: 'Search visible workspace files for matching lines, then use view for a focused window around the hit.',
    actions: ['read'],
    pathScopes: ['.'],
    requiresApproval: false,
  },
  fetch: {
    id: 'fetch',
    name: 'Fetch',
    description: 'Fetch a URL and return its response body.',
    actions: ['read'],
    pathScopes: [],
    requiresApproval: false,
  },
  download: {
    id: 'download',
    name: 'Download',
    description: 'Download a URL into a workspace file.',
    actions: ['write'],
    pathScopes: ['.'],
    requiresApproval: true,
  },
  shell: {
    id: 'shell',
    name: 'Shell',
    description: 'Run local commands inside the organization workspace for builds, tests, git, and real CLI work. Do not create or edit files with shell redirection, heredocs, sed/perl/python scripts, or tee; use write, edit, or multiedit.',
    actions: ['execute'],
    pathScopes: ['.'],
    requiresApproval: true,
  },
  web_search: {
    id: 'web_search',
    name: 'Web Search',
    description: 'Search the web for live results using a provider-backed search path with DuckDuckGo fallback.',
    actions: ['read'],
    pathScopes: [],
    requiresApproval: false,
  },
  schedule: {
    id: 'schedule',
    name: 'Schedule',
    description: 'Create, list, or cancel recurring schedules for an organization.',
    actions: ['read', 'execute'],
    pathScopes: [],
    requiresApproval: false,
  },
  'channel.reply': {
    id: 'channel.reply',
    name: 'Channel Reply',
    description: 'Reply to a message inside its existing thread. Use only when this turn is ready to end; if you still have work to do, keep working instead of calling a terminating tool.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  'channel.list': {
    id: 'channel.list',
    name: 'Channel List',
    description: 'List visible channels in the organization.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  'channel.read': {
    id: 'channel.read',
    name: 'Channel Read',
    description: 'Read recent or searched messages from a channel.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  'channel.close': {
    id: 'channel.close',
    name: 'Channel Close',
    description: 'Silently stand down and end the current turn. Use only when there is nothing else to do; if you still have work to do, keep working instead of closing.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  'channel.recall': {
    id: 'channel.recall',
    name: 'Channel Recall',
    description: 'Search across visible channel history and workspace memory-bank artifacts for prior discussion.',
    actions: ['read'],
    pathScopes: [],
    requiresApproval: false,
  },
  'channel.set_member_mode': {
    id: 'channel.set_member_mode',
    name: 'Channel Set Member Mode',
    description: 'Set a member participation mode in a channel.',
    actions: ['update'],
    pathScopes: [],
    requiresApproval: false,
  },
  'goal.start': {
    id: 'goal.start',
    name: 'Goal Start',
    description: 'Open the channel goal board with a plan and a task list. Use ONLY for kicking off a fresh project; once the goal exists, evolve it via goal_task_update (do not call goal_start twice for the same plan).',
    actions: ['create'],
    pathScopes: [],
    requiresApproval: false,
  },
  'goal.task.update': {
    id: 'goal.task.update',
    name: 'Goal Task Update',
    description: 'Update a task by task_id. Use it to change status or handover_summary; supervisors can also edit title, description, or assignee_id.',
    actions: ['update'],
    pathScopes: [],
    requiresApproval: false,
  },
  'question.ask': {
    id: 'question.ask',
    name: 'Question Ask',
    description: 'Pose a structured multiple-choice question to a human and pause the run until they pick an option.',
    actions: ['create'],
    pathScopes: [],
    requiresApproval: false,
  },
  'memory.write': {
    id: 'memory.write',
    name: 'Memory Write',
    description: 'Save a durable memory fact, decision, action summary, or correction to persist across runs and channels.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  'memory.recall': {
    id: 'memory.recall',
    name: 'Memory Recall',
    description: 'Recall active memories to maintain cross-spirit consistency across DMs and channels.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  'memory.forget': {
    id: 'memory.forget',
    name: 'Memory Forget',
    description: 'Delete a stored memory entry by key.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  procedure: {
    id: 'procedure',
    name: 'Procedure',
    description: 'Add, update, remove, list, or view procedures for self, org, channel, or agent scopes.',
    actions: ['message'],
    pathScopes: [],
    requiresApproval: false,
  },
  mcp: {
    id: 'mcp',
    name: 'MCP',
    description: 'Call an approved MCP server by mcpServerId and toolName. Pass tool arguments in args.',
    actions: ['mcp'],
    pathScopes: [],
    requiresApproval: true,
  },
  'skill.read': {
    id: 'skill.read',
    name: 'Skill Read',
    description: 'Load the full instructions for an installed skill by its name. Call this when you see a skill listed in <available_skills> and want to follow its instructions.',
    actions: ['read'],
    pathScopes: [],
    requiresApproval: false,
  },
  'agent.delegate': {
    id: 'agent.delegate',
    name: 'Agent Delegate',
    description: 'Delegate work to another agent, then wait, inspect status, read, stop, or follow up on that delegate task.',
    actions: ['execute'],
    pathScopes: [],
    requiresApproval: false,
  },
};

export const PERSONALITY_PRESETS: Record<string, PersonalityPreset> = {
  direct: {
    name: 'direct',
    title: 'Direct',
    description: 'Brief, decisive, and low on fluff.',
    instructions:
      'Speak plainly and get to the point. Prefer short, actionable responses. Do not over-explain when a clear answer exists.',
  },
  thoughtful: {
    name: 'thoughtful',
    title: 'Thoughtful',
    description: 'Balances action with careful consideration.',
    instructions:
      'Slow down enough to notice tradeoffs and hidden assumptions. When the answer is uncertain, say so and explain the decision path.',
  },
  precise: {
    name: 'precise',
    title: 'Precise',
    description: 'Exact, rigorous, and detail-oriented.',
    instructions:
      'Be exact about names, numbers, paths, and constraints. Avoid vague language. Call out anything that needs verification.',
  },
  warm: {
    name: 'warm',
    title: 'Warm',
    description: 'Collaborative and easy to work with.',
    instructions:
      'Be friendly and encouraging without losing clarity. Help the team move forward with a calm, human tone.',
  },
  skeptical: {
    name: 'skeptical',
    title: 'Skeptical',
    description: 'Questions assumptions and looks for failure modes.',
    instructions:
      'Pressure-test claims, look for edge cases, and challenge unsafe or unproven plans. Prefer proof over optimism.',
  },
  pragmatic: {
    name: 'pragmatic',
    title: 'Pragmatic',
    description: 'Biases toward the simplest working path.',
    instructions:
      'Choose the smallest implementation that solves the problem. Avoid unnecessary abstraction and keep decisions grounded in current constraints.',
  },
};

export { ROLE_PRESETS };
